---
description: Application configuration file for Faitour 2.0

# Network details for binding NFQueue and sockets
network:
  max_queue_size: 10240
  adapter:
    name: change_me
    ip: 10.0.0.0
    mac: 00:11:22:33:44:55

# Logging configuration
logging:
  level: INFO    # DEBUG, INFO, WARN, ERROR, CRITICAL
  stdout:
    enabled: True
  file:
    enabled: True
    path: /var/log/faitour/
    size: 10000000
    count: 10

# Certificate details for HTTPS (and RDP?)
tls:
  country_name: US
  state: California
  locality: Los Angeles
  organization: Example Org
  common_name: foo.example.org

# Logging SYN requests will allow port scan detection in Elastic
syn_logging:
  tcp: True

# Operating system to spoof
operating_system:
  name: Microsoft Windows Server 2008 R2
  fingerprint: |
      SEQ(SP=FC-106%GCD=1-6%ISR=103-10D%TI=I|RD%CI=I%II=I%SS=S%TS=7|A)
      OPS(O1=M5B4NW8ST11%O2=M5B4NW8ST11%O3=M5B4NW8NNT11%O4=M5B4NW8ST11%O5=M5B4NW8ST11%O6=M5B4ST11)
      WIN(W1=2000%W2=2000%W3=2000%W4=2000%W5=2000%W6=2000)
      ECN(R=Y%DF=Y%T=7A-84%TG=80%W=2000%O=M5B4NW8NNS%CC=N%Q=)
      T1(R=Y%DF=Y%T=7A-84%TG=80%S=O%A=S+%F=AS%RD=0%Q=)
      T2(R=Y%DF=Y%T=7A-84%TG=80%W=0%S=Z%A=S%F=AR%O=%RD=0%Q=)
      T3(R=Y%DF=Y%T=7A-84%TG=80%W=0%S=Z%A=O%F=AR%O=%RD=0%Q=)
      T4(R=Y%DF=Y%T=7A-84%TG=80%W=0%S=A%A=O%F=R%O=%RD=0%Q=)
      T5(R=Y%DF=Y%T=7A-84%TG=80%W=0%S=Z%A=S+%F=AR%O=%RD=0%Q=)
      T6(R=Y%DF=Y%T=7A-84%TG=80%W=0%S=A%A=O%F=R%O=%RD=0%Q=)
      T7(R=Y%DF=Y%T=7A-84%TG=80%W=0%S=Z%A=S+%F=AR%O=%RD=0%Q=)
      U1(DF=N%T=7A-84%TG=80%IPL=164%UN=0%RIPL=G%RID=G%RIPCK=Z%RUCK=0%RUD=G)
      IE(DFI=N%T=7A-84%TG=80%CD=Z)

# Services to emulate and/or spoof
services:
  - name: ftp
    enabled: False
    port: 21
    username: admin
    password: admin
    system_type: Windows    # Returns on "SYST" call (Windows, Unix, Linux, etc.)
    banner: |
        IIS 7.5 FTP
  - name: ssh
    enabled: False
    port: 22
    username: admin
    password: admin
    hostname: hrrecords   # Shown on the bash prompt
    login_banner: |
        \r\n**********************************\r\nThis is a private server!\r\nUnauthorized access is prohibited!\r\n**********************************\r\n
    fingerprint: |
        SSH-2.0-OpenSSH_for_Windows_9.5
  - name: telnet
    enabled: False
    port: 23
    username: admin
    password: admin
    allow_anonymous: True
    login_banner: |
        Microsoft telnet server ready.
    fingerprint: |
        \xff\xfd\x25\xff\xfb\x01\xff\xfb\x03\xff\xfd\x27\xff\xfd\x1f\xff\xfd\x00\xff\xfb\x00
  - name: http
    enabled: True
    port: 80
    username: admin   # Also applies to HTTPS
    password: admin   # Also applies to HTTPS
    default_doc: index.html   # Also applies to HTTPS
    server_header: Microsoft-IIS/7.5
    fingerprint: |
        HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nLast-Modified: Thu, 23 Jan 2025 03:52:09 GMT\r\nAccept-Ranges: bytes\r\nETag: "4e0532d4a6ddb1:0"\r\nServer: Microsoft-IIS/7.5\r\n
  - name: rpc
    enabled: True
    port: 135
    fingerprint: |
        \x05\0\r\x03\x10\0\0\0\x18\0\0\0....\x04\0\x01\x05\0...
  - name: netbios
    enabled: True
    port: 139
    fingerprint: |
        \x83\0\0\x01\x8f
  - name: snmp
    enabled: False
    port: 161
    community: Public SNMP Emulator v9.9.9
    fingerprint: |
        0.36\x02\x01\0\x04\x06public\xa2
  - name: https
    enabled: True
    port: 443
    username: # Set under HTTP
    password: # Set under HTTP
    default_doc: # Set under HTTP
    server_header: # Set under HTTP
    fingerprint: |
        HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nLast-Modified: Thu, 23 Jan 2025 03:52:09 GMT\r\nAccept-Ranges: bytes\r\nETag: "4e0532d4a6ddb1:0"\r\nServer: Microsoft-IIS/7.5\r\n
  - name: smb
    enabled: True
    port: 445
    fingerprint: |
        \0\0\0a\xffSMBr\0\0\0\0\x88\x01@\0\0\0\0\0\0\0\0\0\0\0\0\0\0@\x06\0\0\x01\0\x11\x07\0a2\0\x01\0\x04A\0\0\0\0\x01\0\0\0\0\0\xfd\xe3\x01\0ABCDEFGHIJKLMNOPQRSTU\0\0\0\0
  - name: mssql
    enabled: False
    port: 1433
    fingerprint: |
        \x04\x01\x00\x25\x00\x00\x01\x00\x00\x00\x15\x00\x06\x01\x00\x1b\x00\x01\x02\x00\x1c\x00\x01\x03\x00\x1d\x00\x00\xff\x0b\x00\x13\xc2
  - name: mysql
    enabled: False
    port: 3306
    fingerprint: |
        X\0\0\0\x0a8.3.0\0ABC\0
  - name: rdp
    enabled: False
    port: 3389
    fingerprint: |
        \x03\0\0\x0b\x06\xd0\0\0\x124\0
  - name: postgresql
    enabled: False
    port: 5432
    fingerprint: |
        EInvalid packet length\0
